all: nbc

nbc:
	cd src/NXT && make all
	cp src/NXT/nbc .

# prog
progclean:
	rm -rf nbc

# just clean the file generated by the compiler (*.o, ...)
clean: progclean
	cd src/NXT && make clean

# clean the programs as well
realclean: progclean
	cd src/NXT && make realclean
